### PR TITLE
[WIP] 2016 Spring Web Environment by at15

### PR DESCRIPTION
**Pull request by at15**
#1 was merged in order to show the sketch of the lecture, it is still working in progress

you can view it [here](http://course.readthedocs.org/en/latest/web/2016-spring/environment/index.html) but since read the docs does not support branches, it's quite useless before this pr got merged.
- [x] introduction to develop environment, local, production, staging, qa etc [preview](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/env.rst)
- [x] workspace setup, how to organize your code [preview](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/workspace.md)
- [x] editor [preview](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/editor.md)
- [ ] command line [draft](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/cmd.md)
- [ ] virtual machine [draft](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/virtual.md)
- [ ] vagrant [draft](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/vagrant.md)
- [ ] request [draft](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/request.md)
- [ ] linux [draft](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/linux.md)
- [ ] nginx [draft](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/nginx.md)
- [ ] php [draft](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/php.md)
- [x] homework [preview](https://github.com/dyweb/course/blob/2016-spring/web-env-at15/web/2016-spring/environment/homework.md)

### CODE REVIEW

**Comment by ComMouse** [comment]
...

**Comment by at15** [comment]
need to mention how to change vagrant box and virtual machine location, in order to save disk space on C. 
- https://www.vagrantup.com/docs/other/environmental-variables.html  change VAGRANT_HOME to change vagrant.d folder location
- then change virtual box default vm location to change created vm location

also private network might be a better solution than port forwarding

**Comment by ComMouse** [comment]
@at15

**Comment by at15** [comment]
..... I don't think I have time ...

**Comment by ComMouse** [comment]
Just resolve the conflict..... no new stuff required...

**Pull request merged**
