### PR TITLE
Include EditorConfig

### PR DESCRIPTION
**Pull request by arrowrowe**
Need a force-check. Maybe we should write a editorconfig plugin for [Textlint](https://github.com/textlint/textlint) someday.

But this will do for now.

### CODE REVIEW

**Comment by at15** [comment]
e... actually, you should make a pr for 2016-spring/web-env-at15 branch, since a lot of documentations were added in that branch. As for master branch LGTM.

**Comment by arrowrowe** [comment]
re @at15 There's 3 conflicts between `2016-spring/web-env-at15` and `master`. Maybe you have to rebase it yourself......

```
gcm
gl
gco 2016-spring/web-env-at15
grbm
# Resolve all conflicts
gaa
grb --continue
gp -f
```

For ~~OMZ haters~~ those who don't have OMZ,

```
git checkout master
git pull origin master
git checkout 2016-spring/web-env-at15
git rebase master
# Resolve all conflicts
git add --all
git rebase --continue
git push -f
```

**Comment by at15** [comment]
@arrowrowe I don't have omz in gitbash, so no `gxx`

**Comment by arrowrowe** [comment]
re @at15 I've updated.

**Comment by at15** [comment]
@arrowrowe I don't have does not mean I hate, like I don't have a gf ....

**Pull request merged**
