### PR TITLE
mos: Add Docker slides

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by at15** [comment]
reject! 

LGTM

**Review by at15 — COMMENTED** [review]
so how long is the lecture?

**Comment by gaocegege** [comment]
@at15 < 30 min

**Review by at15 — APPROVED** [review]
LGTM

**Comment by ComMouse** [comment]
LGTM

**Pull request merged**
